package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path"
	"strings"

	"github.com/varlink/go/varlink/idl"
)

type methodMode string

const (
	modeUnary   methodMode = "unary"
	modeStream  methodMode = "stream"
	modeOneway  methodMode = "oneway"
	modeUpgrade methodMode = "upgrade"
)

type methodSpec struct {
	Method *idl.Method
	Mode   methodMode
}

func writeTypeV2(b *bytes.Buffer, t *idl.Type, jsonTags bool, indent int) {
	switch t.Kind {
	case idl.TypeBool:
		b.WriteString("bool")
	case idl.TypeInt:
		b.WriteString("int64")
	case idl.TypeFloat:
		b.WriteString("float64")
	case idl.TypeString, idl.TypeEnum:
		b.WriteString("string")
	case idl.TypeObject:
		b.WriteString("json.RawMessage")
	case idl.TypeAny:
		b.WriteString("any")
	case idl.TypeArray:
		b.WriteString("[]")
		writeTypeV2(b, t.ElementType, jsonTags, indent)
	case idl.TypeMap:
		b.WriteString("map[string]")
		writeTypeV2(b, t.ElementType, jsonTags, indent)
	case idl.TypeMaybe:
		b.WriteString("*")
		writeTypeV2(b, t.ElementType, jsonTags, indent)
	case idl.TypeAlias:
		b.WriteString(t.Alias)
	case idl.TypeStruct:
		if len(t.Fields) == 0 {
			b.WriteString("struct{}")
			return
		}
		b.WriteString("struct {\n")
		for _, field := range t.Fields {
			for i := 0; i < indent+1; i++ {
				b.WriteString("\t")
			}
			b.WriteString(goFieldName(field.Name))
			b.WriteByte(' ')
			writeTypeV2(b, field.Type, jsonTags, indent+1)
			if jsonTags {
				b.WriteString(" `json:\"")
				b.WriteString(field.Name)
				if field.Type.Kind == idl.TypeMaybe {
					b.WriteString(",omitempty")
				}
				b.WriteString("\"`")
			}
			b.WriteByte('\n')
		}
		for i := 0; i < indent; i++ {
			b.WriteString("\t")
		}
		b.WriteByte('}')
	}
}

func writeDocComment(b *bytes.Buffer, doc string) {
	if doc == "" {
		return
	}
	for _, line := range strings.Split(doc, "\n") {
		b.WriteString("// ")
		b.WriteString(line)
		b.WriteByte('\n')
	}
}

func goFieldName(name string) string {
	if name == "" {
		return ""
	}
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, "")
}

func methodInputName(name string) string  { return name + "Request" }
func methodOutputName(name string) string { return name + "Reply" }

func parseMethodMode(doc string) (methodMode, error) {
	mode := modeUnary
	for _, line := range strings.Split(doc, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "@mode") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) != 2 {
			return "", fmt.Errorf("invalid @mode directive %q", line)
		}
		switch methodMode(fields[1]) {
		case modeUnary, modeStream, modeOneway, modeUpgrade:
			mode = methodMode(fields[1])
		default:
			return "", fmt.Errorf("unknown method mode %q", fields[1])
		}
	}
	return mode, nil
}

func generateTemplateV2(description string) (string, []byte, error) {
	description = strings.TrimRight(description, "\n")

	midl, err := idl.New(description)
	if err != nil {
		return "", nil, err
	}

	methods := make([]methodSpec, 0, len(midl.Methods))
	needBatch := false
	needUpgrade := false
	for _, m := range midl.Methods {
		mode, err := parseMethodMode(m.Doc)
		if err != nil {
			return "", nil, fmt.Errorf("method %s: %w", m.Name, err)
		}
		methods = append(methods, methodSpec{Method: m, Mode: mode})
		if mode == modeUnary || mode == modeOneway {
			needBatch = true
		}
		if mode == modeUpgrade {
			needUpgrade = true
		}
	}

	pkgname := strings.ToLower(strings.ReplaceAll(midl.Name, ".", ""))
	var b bytes.Buffer

	b.WriteString("// Code generated by github.com/varlink/go/cmd/varlink-go-interface-generator-v2, DO NOT EDIT.\n\n")
	writeDocComment(&b, midl.Doc)
	b.WriteString("package " + pkgname + "\n\n")
	b.WriteString("@IMPORTS@\n\n")

	b.WriteString("const InterfaceName = `" + midl.Name + "`\n\n")
	b.WriteString("const InterfaceDescription = `" + strings.ReplaceAll(midl.Description, "`", "` + \"`\" + `") + "\n`\n\n")

	b.WriteString("// Generated type declarations\n\n")
	for _, a := range midl.Aliases {
		writeDocComment(&b, a.Doc)
		b.WriteString("type " + a.Name + " ")
		writeTypeV2(&b, a.Type, true, 0)
		b.WriteString("\n\n")
	}

	b.WriteString("// Generated method request/reply declarations\n\n")
	for _, m := range methods {
		writeDocComment(&b, m.Method.Doc)
		b.WriteString("type " + methodInputName(m.Method.Name) + " ")
		writeTypeV2(&b, m.Method.In, true, 0)
		b.WriteString("\n\n")
		b.WriteString("type " + methodOutputName(m.Method.Name) + " ")
		writeTypeV2(&b, m.Method.Out, true, 0)
		b.WriteString("\n\n")
	}

	b.WriteString("// Generated error declarations\n\n")
	for _, e := range midl.Errors {
		writeDocComment(&b, e.Doc)
		b.WriteString("type " + e.Name + " ")
		writeTypeV2(&b, e.Type, true, 0)
		b.WriteString("\n\n")
		b.WriteString("func (e " + e.Name + ") Error() string {\n")
		b.WriteString("\treturn InterfaceName + \".\" + \"" + e.Name + "\"\n")
		b.WriteString("}\n\n")
	}

	b.WriteString("func DispatchError(err error) error {\n")
	b.WriteString("\tvar remote *varlink.RemoteError\n")
	b.WriteString("\tif !errors.As(err, &remote) {\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tswitch remote.Name {\n")
	for _, e := range midl.Errors {
		b.WriteString("\tcase InterfaceName + \".\" + \"" + e.Name + "\":\n")
		b.WriteString("\t\tvar out " + e.Name + "\n")
		b.WriteString("\t\tif decodeErr := remote.Decode(&out); decodeErr != nil {\n")
		b.WriteString("\t\t\treturn err\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\treturn &out\n")
	}
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("type Client struct {\n")
	b.WriteString("\tclient varlink.Client\n")
	b.WriteString("}\n\n")
	b.WriteString("func NewClient(client varlink.Client) *Client {\n")
	b.WriteString("\treturn &Client{client: client}\n")
	b.WriteString("}\n\n")
	b.WriteString("func (c *Client) Close() error {\n")
	b.WriteString("\tif c == nil || c.client == nil {\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn c.client.Close()\n")
	b.WriteString("}\n\n")

	if needBatch {
		b.WriteString("type ClientBatch struct {\n")
		b.WriteString("\tbatch varlink.Batch\n")
		b.WriteString("}\n\n")
		b.WriteString("func (c *Client) Batch() *ClientBatch {\n")
		b.WriteString("\treturn &ClientBatch{batch: c.client.Batch()}\n")
		b.WriteString("}\n\n")
		b.WriteString("func (b *ClientBatch) Send(ctx context.Context) error {\n")
		b.WriteString("\treturn b.batch.Send(ctx)\n")
		b.WriteString("}\n\n")
	}

	for _, m := range methods {
		inName := methodInputName(m.Method.Name)
		outName := methodOutputName(m.Method.Name)

		switch m.Mode {
		case modeUnary:
			b.WriteString("func (c *Client) " + m.Method.Name + "(ctx context.Context, in " + inName + ") (" + outName + ", error) {\n")
			b.WriteString("\tvar out " + outName + "\n")
			b.WriteString("\terr := c.client.Invoke(ctx, InterfaceName+\"." + m.Method.Name + "\", in, &out)\n")
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\treturn " + outName + "{}, DispatchError(err)\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn out, nil\n")
			b.WriteString("}\n\n")
			if needBatch {
				b.WriteString("func (b *ClientBatch) " + m.Method.Name + "(in " + inName + ", out *" + outName + ") {\n")
				b.WriteString("\tb.batch.Invoke(InterfaceName+\"." + m.Method.Name + "\", in, out)\n")
				b.WriteString("}\n\n")
			}
		case modeOneway:
			b.WriteString("func (c *Client) " + m.Method.Name + "(ctx context.Context, in " + inName + ") error {\n")
			b.WriteString("\treturn DispatchError(c.client.Oneway(ctx, InterfaceName+\"." + m.Method.Name + "\", in))\n")
			b.WriteString("}\n\n")
			if needBatch {
				b.WriteString("func (b *ClientBatch) " + m.Method.Name + "(in " + inName + ") {\n")
				b.WriteString("\tb.batch.Oneway(InterfaceName+\"." + m.Method.Name + "\", in)\n")
				b.WriteString("}\n\n")
			}
		case modeStream:
			b.WriteString("type " + m.Method.Name + "ReplyStream struct {\n")
			b.WriteString("\tstream varlink.Stream\n")
			b.WriteString("}\n\n")
			b.WriteString("func (c *Client) " + m.Method.Name + "(ctx context.Context, in " + inName + ") (*" + m.Method.Name + "ReplyStream, error) {\n")
			b.WriteString("\tstream, err := c.client.Stream(ctx, InterfaceName+\"." + m.Method.Name + "\", in)\n")
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\treturn nil, DispatchError(err)\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn &" + m.Method.Name + "ReplyStream{stream: stream}, nil\n")
			b.WriteString("}\n\n")
			b.WriteString("func (s *" + m.Method.Name + "ReplyStream) Recv(ctx context.Context) (" + outName + ", error) {\n")
			b.WriteString("\tvar out " + outName + "\n")
			b.WriteString("\tif err := s.stream.Recv(ctx, &out); err != nil {\n")
			b.WriteString("\t\treturn " + outName + "{}, DispatchError(err)\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn out, nil\n")
			b.WriteString("}\n\n")
			b.WriteString("func (s *" + m.Method.Name + "ReplyStream) Close() error {\n")
			b.WriteString("\tif s == nil || s.stream == nil {\n")
			b.WriteString("\t\treturn nil\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn s.stream.Close()\n")
			b.WriteString("}\n\n")
		case modeUpgrade:
			b.WriteString("func (c *Client) " + m.Method.Name + "(ctx context.Context, in " + inName + ") (" + outName + ", varlink.UpgradedConn, error) {\n")
			b.WriteString("\tvar out " + outName + "\n")
			b.WriteString("\tconn, err := c.client.Upgrade(ctx, InterfaceName+\"." + m.Method.Name + "\", in, &out)\n")
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\treturn " + outName + "{}, nil, DispatchError(err)\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn out, conn, nil\n")
			b.WriteString("}\n\n")
		}
	}

	b.WriteString("type UnaryCall struct{ varlink.UnaryCall }\n\n")
	b.WriteString("type StreamCall struct{ varlink.StreamCall }\n\n")
	b.WriteString("type UpgradeCall struct{ varlink.UpgradeCall }\n\n")

	for _, e := range midl.Errors {
		for _, callType := range []string{"UnaryCall", "StreamCall", "UpgradeCall"} {
			b.WriteString("func (c " + callType + ") Reply" + e.Name + "(ctx context.Context, out " + e.Name + ") error {\n")
			b.WriteString("\treturn c.ReplyError(ctx, InterfaceName+\"." + e.Name + "\", out)\n")
			b.WriteString("}\n\n")
		}
	}

	for _, m := range methods {
		outName := methodOutputName(m.Method.Name)
		switch m.Mode {
		case modeUnary, modeOneway:
			b.WriteString("func (c UnaryCall) Reply" + m.Method.Name + "(ctx context.Context, out " + outName + ") error {\n")
			b.WriteString("\treturn c.Reply(ctx, out)\n")
			b.WriteString("}\n\n")
		case modeStream:
			b.WriteString("func (c StreamCall) Send" + m.Method.Name + "(ctx context.Context, out " + outName + ") error {\n")
			b.WriteString("\treturn c.Send(ctx, out)\n")
			b.WriteString("}\n\n")
			b.WriteString("func (c StreamCall) Close" + m.Method.Name + "(ctx context.Context, out " + outName + ") error {\n")
			b.WriteString("\treturn c.Close(ctx, out)\n")
			b.WriteString("}\n\n")
		case modeUpgrade:
			b.WriteString("func (c UpgradeCall) Accept" + m.Method.Name + "(ctx context.Context, out " + outName + ") (io.ReadWriteCloser, error) {\n")
			b.WriteString("\treturn c.Accept(ctx, out)\n")
			b.WriteString("}\n\n")
		}
	}

	b.WriteString("type Handler interface {\n")
	for _, m := range methods {
		switch m.Mode {
		case modeUnary, modeOneway:
			b.WriteString("\t" + m.Method.Name + "(ctx context.Context, call UnaryCall, in " + methodInputName(m.Method.Name) + ") error\n")
		case modeStream:
			b.WriteString("\t" + m.Method.Name + "(ctx context.Context, call StreamCall, in " + methodInputName(m.Method.Name) + ") error\n")
		case modeUpgrade:
			b.WriteString("\t" + m.Method.Name + "(ctx context.Context, call UpgradeCall, in " + methodInputName(m.Method.Name) + ") error\n")
		}
	}
	b.WriteString("}\n\n")

	b.WriteString("func RegisterDescription(builder *varlink.ServerBuilder) error {\n")
	b.WriteString("\treturn builder.SetInterfaceDescription(InterfaceName, InterfaceDescription)\n")
	b.WriteString("}\n\n")

	b.WriteString("func Register(builder *varlink.ServerBuilder, impl Handler) error {\n")
	b.WriteString("\tif err := RegisterDescription(builder); err != nil {\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n")
	for _, m := range methods {
		inName := methodInputName(m.Method.Name)
		switch m.Mode {
		case modeUnary, modeOneway:
			b.WriteString("\tif err := builder.RegisterUnary(InterfaceName, \"" + m.Method.Name + "\", func(ctx context.Context, call varlink.UnaryCall) error {\n")
		case modeStream:
			b.WriteString("\tif err := builder.RegisterStream(InterfaceName, \"" + m.Method.Name + "\", func(ctx context.Context, call varlink.StreamCall) error {\n")
		case modeUpgrade:
			b.WriteString("\tif err := builder.RegisterUpgrade(InterfaceName, \"" + m.Method.Name + "\", func(ctx context.Context, call varlink.UpgradeCall) error {\n")
		}
		b.WriteString("\t\tvar in " + inName + "\n")
		b.WriteString("\t\tif err := call.Decode(&in); err != nil {\n")
		b.WriteString("\t\t\treturn err\n")
		b.WriteString("\t\t}\n")
		switch m.Mode {
		case modeUnary, modeOneway:
			b.WriteString("\t\treturn impl." + m.Method.Name + "(ctx, UnaryCall{call}, in)\n")
		case modeStream:
			b.WriteString("\t\treturn impl." + m.Method.Name + "(ctx, StreamCall{call}, in)\n")
		case modeUpgrade:
			b.WriteString("\t\treturn impl." + m.Method.Name + "(ctx, UpgradeCall{call}, in)\n")
		}
		b.WriteString("\t}); err != nil {\n")
		b.WriteString("\t\treturn err\n")
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")

	ret := b.String()
	imports := []string{
		"\"context\"",
		"\"errors\"",
		"\"github.com/varlink/go/v2/varlink\"",
	}
	if strings.Contains(ret, "json.RawMessage") {
		imports = append(imports, "\"encoding/json\"")
	}
	if needUpgrade {
		imports = append(imports, "\"io\"")
	}
	ret = strings.Replace(ret, "@IMPORTS@", "import (\n\t"+strings.Join(imports, "\n\t")+"\n)", 1)

	pretty, err := format.Source([]byte(ret))
	if err != nil {
		return "", nil, err
	}
	return pkgname, pretty, nil
}

func generateFileV2(varlinkFile string) error {
	file, err := os.ReadFile(varlinkFile)
	if err != nil {
		return err
	}
	pkgname, content, err := generateTemplateV2(string(file))
	if err != nil {
		return err
	}
	filename := path.Join(path.Dir(varlinkFile), pkgname+".go")
	return os.WriteFile(filename, content, 0o660)
}

func main() {
	if len(os.Args) != 2 {
		fmt.Printf("Usage: %s <file>\n", os.Args[0])
		os.Exit(1)
	}
	if err := generateFileV2(os.Args[1]); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}
